spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/image_station?serverTimezone=GMT%2b8
    username: root
    password: 123456

Server:
#  ip: localhost
  ip: 172.19.5.219
  port: 9090


config:
  Swagger3:
    flag: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:\_Jinan\graduation_project\work_space\DIP\FileStore\
